/*
 * This source file was generated by the Gradle 'init' task
 */
package org.snake;

import org.junit.Test;
import org.snake.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
